---
title: "parametric_bootstrap"
author: "u7627793 Yutong Shao"
date: "2025-04-22"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
```


## 1. Parametric bootstrap test of full-crossing models


```{r}
# Poisson exchangeability

Poisson_C60fix <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-C60fix/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_C60opt <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-C60opt/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_C10fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-C10fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_C10optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-C10opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_C60fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-C60fix-PMSF/homo_tree/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_C60optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-C60opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_UDM8fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-UDM8fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_UDM8optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-UDM8opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_UDM64fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-UDM64fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_UDM64optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-UDM64opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_UDM128fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-UDM128fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_UDM128optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-UDM128opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_MEOW10optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-MEOW10opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_MEOW60optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-MEOW60opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_MEOW120optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-MEOW120opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# LG exchangeability

LG_C60fix <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-C60fix/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_C10fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-C10fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_C10optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-C10opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_C60fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-C60fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_C60optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-C60opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM8fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-UDM8fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM8optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-UDM8opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM64fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-UDM64HOC-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM64optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-UDM64opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM128fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-UDM128fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM128optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-UDM128opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_MEOW10optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-MEOW10opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_MEOW60optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-MEOW60opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_MEOW120optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-MEOW120opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# GTR20 exchangeability

GTR20_C10fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/GTR20-C10fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

GTR20_C10optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/GTR20-C10opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

GTR20_C60fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/GTR20-C60fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

GTR20_C60optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/GTR20-C60opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

GTR20_UDM8fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/GTR20-UDM8fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

GTR20_UDM8optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/GTR20-UDM8opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

GTR20_UDM64fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/GTR20-UDM64fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

GTR20_UDM64optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/GTR20-UDM64opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

GTR20_UDM128fixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/GTR20-UDM128fix-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

GTR20_UDM128optPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/GTR20-UDM128opt-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# CAT-PMSF

Poisson_CAT_PMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-CAT-PMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# Add label

marked_x <- 4.395595869540684

Poisson_CAT_PMSF$dataset <- "Poisson-CAT-PMSF"

Poisson_C60fix$dataset <- "Poisson+C60fix"
Poisson_C60opt$dataset <- "Poisson+C60opt"
Poisson_C10fixPMSF$dataset <- "Poisson+C10fix-PMSF"
Poisson_C10optPMSF$dataset <- "Poisson+C10opt-PMSF"
Poisson_C60fixPMSF$dataset <- "Poisson+C60fix-PMSF"
Poisson_C60optPMSF$dataset <- "Poisson+C60opt-PMSF"
Poisson_UDM8fixPMSF$dataset <- "Poisson+UDM8fix-PMSF"
Poisson_UDM8optPMSF$dataset <- "Poisson+UDM8opt-PMSF"
Poisson_UDM64fixPMSF$dataset <- "Poisson+UDM64fix-PMSF"
Poisson_UDM64optPMSF$dataset <- "Poisson+UDM64opt-PMSF"
Poisson_UDM128fixPMSF$dataset <- "Poisson+UDM128fix-PMSF"
Poisson_UDM128optPMSF$dataset <- "Poisson+UDM128opt-PMSF"
Poisson_MEOW10optPMSF$dataset <- "Poisson+MEOW10opt-PMSF"
Poisson_MEOW60optPMSF$dataset <- "Poisson+MEOW60opt-PMSF"
Poisson_MEOW120optPMSF$dataset <- "Poisson+MEOW120opt-PMSF"

LG_C60fix$dataset <- "LG+C60fix"
LG_C10fixPMSF$dataset <- "LG+C10fix-PMSF"
LG_C10optPMSF$dataset <- "LG+C10opt-PMSF"
LG_C60fixPMSF$dataset <- "LG+C60fix-PMSF"
LG_C60optPMSF$dataset <- "LG+C60opt-PMSF"
LG_UDM8fixPMSF$dataset <- "LG+UDM8fix-PMSF"
LG_UDM8optPMSF$dataset <- "LG+UDM8opt-PMSF"
LG_UDM64fixPMSF$dataset <- "LG+UDM64fix-PMSF"
LG_UDM64optPMSF$dataset <- "LG+UDM64opt-PMSF"
LG_UDM128fixPMSF$dataset <- "LG+UDM128fix-PMSF"
LG_UDM128optPMSF$dataset <- "LG+UDM128opt-PMSF"
LG_MEOW10optPMSF$dataset <- "LG+MEOW10opt-PMSF"
LG_MEOW60optPMSF$dataset <- "LG+MEOW60opt-PMSF"
LG_MEOW120optPMSF$dataset <- "LG+MEOW120opt-PMSF"

GTR20_C10fixPMSF$dataset <- "GTR20+C10fix-PMSF"
GTR20_C10optPMSF$dataset <- "GTR20+C10opt-PMSF"
GTR20_C60fixPMSF$dataset <- "GTR20+C60fix-PMSF"
GTR20_C60optPMSF$dataset <- "GTR20+C60opt-PMSF"
GTR20_UDM8fixPMSF$dataset <- "GTR20+UDM8fix-PMSF"
GTR20_UDM8optPMSF$dataset <- "GTR20+UDM8opt-PMSF"
GTR20_UDM64fixPMSF$dataset <- "GTR20+UDM64fix-PMSF"
GTR20_UDM64optPMSF$dataset <- "GTR20+UDM64opt-PMSF"
GTR20_UDM128fixPMSF$dataset <- "GTR20+UDM128fix-PMSF"
GTR20_UDM128optPMSF$dataset <- "GTR20+UDM128opt-PMSF"

combined_data <- rbind(Poisson_CAT_PMSF, Poisson_C60fix, Poisson_C60opt, Poisson_C10fixPMSF, Poisson_C10optPMSF, Poisson_C60fixPMSF, Poisson_C60optPMSF, Poisson_UDM8fixPMSF, Poisson_UDM8optPMSF, Poisson_UDM64fixPMSF, Poisson_UDM64optPMSF, Poisson_UDM128fixPMSF, Poisson_UDM128optPMSF, Poisson_MEOW10optPMSF, Poisson_MEOW60optPMSF, Poisson_MEOW120optPMSF, LG_C60fix, LG_C10fixPMSF, LG_C10optPMSF, LG_C60fixPMSF, LG_C60optPMSF, LG_UDM8fixPMSF, LG_UDM8optPMSF, LG_UDM64fixPMSF, LG_UDM64optPMSF, LG_UDM128fixPMSF, LG_UDM128optPMSF, LG_MEOW10optPMSF, LG_MEOW60optPMSF, LG_MEOW120optPMSF, GTR20_C10fixPMSF, GTR20_C10optPMSF, GTR20_C60fixPMSF, GTR20_C60optPMSF, GTR20_UDM8fixPMSF, GTR20_UDM8optPMSF, GTR20_UDM64fixPMSF, GTR20_UDM64optPMSF, GTR20_UDM128fixPMSF, GTR20_UDM128optPMSF)
```


```{r}
# Type One

combined_data <- combined_data %>%
  mutate(group = case_when(
    dataset == "Poisson-CAT-PMSF" ~ "CAT-PMSF",
    
    dataset %in% c("GTR20+C10fix-PMSF", "GTR20+C10opt-PMSF", "GTR20+C60fix-PMSF", "GTR20+C60opt-PMSF", "LG+C10fix-PMSF", "LG+C10opt-PMSF","LG+C60fix-PMSF", "LG+C60opt-PMSF", "Poisson+C10fix-PMSF", "Poisson+C10opt-PMSF","Poisson+C60fix-PMSF", "Poisson+C60opt-PMSF") ~ "CXX-PMSF",
    
    dataset %in% c("Poisson+UDM8fix-PMSF", "Poisson+UDM8opt-PMSF", "Poisson+UDM64fix-PMSF", "Poisson+UDM64opt-PMSF", "Poisson+UDM128fix-PMSF", "Poisson+UDM128opt-PMSF", "LG+UDM8fix-PMSF", "LG+UDM8opt-PMSF", "LG+UDM64fix-PMSF", "LG+UDM64opt-PMSF", "LG+UDM128fix-PMSF", "LG+UDM128opt-PMSF", "GTR20+UDM8fix-PMSF", "GTR20+UDM8opt-PMSF", "GTR20+UDM64fix-PMSF", "GTR20+UDM64opt-PMSF", "GTR20+UDM128fix-PMSF", "GTR20+UDM128opt-PMSF") ~ "UDM-PMSF",
    
    dataset %in% c("LG+MEOW10opt-PMSF", "LG+MEOW60opt-PMSF", "LG+MEOW120opt-PMSF", "Poisson+MEOW10opt-PMSF", "Poisson+MEOW60opt-PMSF", "Poisson+MEOW120opt-PMSF") ~ "MEOW-PMSF",
    
    dataset %in% c("Poisson+C60fix", "Poisson+C60opt", "LG+C60fix") ~ "C60",
    TRUE ~ NA_character_
  ))

# Sort the dataset based on the group order

group_order <- c("CAT-PMSF", "CXX-PMSF", "UDM-PMSF", "MEOW-PMSF", "C60")

ordered_dataset_levels <- combined_data %>%
  mutate(group = factor(group, levels = group_order)) %>%
  arrange(group, dataset) %>%
  pull(dataset) %>%
  unique()

combined_data$dataset <- factor(combined_data$dataset, levels = ordered_dataset_levels)

group_lines <- data.frame(
  group = c("CXX-PMSF", "UDM-PMSF", "MEOW-PMSF", "C60"),
  x_start = c(1.6, 13.6, 31.6, 37.6),
  x_end   = c(13.4, 31.4, 37.4, 40.4),
  y       = max(as.numeric(combined_data$diversity), na.rm = TRUE) + 0.05
)

# Plot 1

ggplot(combined_data, aes(x = dataset, y = as.numeric(diversity), fill = dataset)) +
  geom_violin(alpha = 0.6, linewidth = 0.4, color = "black") +
  geom_boxplot(width = 0.2, outlier.shape = NA, linewidth = 0.4, fill = NA, color = "black") +
  geom_hline(yintercept = marked_x, linetype = "dashed", color = "red", linewidth = 0.8) +
  geom_vline(xintercept = c(1.5, 13.5, 31.5, 37.5), linetype = "dotted", color = "grey70", linewidth = 0.5) +
  geom_segment(data = group_lines,
               aes(x = x_start, xend = x_end, y = y, yend = y),
               inherit.aes = FALSE,
               linewidth = 0.5, color = "black") +
  geom_text(
  data = group_lines,
  aes(x = (x_start + x_end)/2, y = y + 0.045, label = group),
  inherit.aes = FALSE,
  size = 3,
  fontface = "plain",
  hjust = 0.5
) +
  labs(x = NULL, y = "div") +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, color = "black", size = 8),
    axis.text.y = element_text(color = "black", size = 10),
    axis.line = element_line(color = "black"),
    legend.position = "none",
    plot.margin = margin(5, 2, 2, 5)
  )
```


```{r}
# Type Two
combined_data <- combined_data %>%
  mutate(group = case_when(
    dataset == "Poisson-CAT-PMSF" ~ "CAT-PMSF",
    
    dataset %in% c("GTR20+C10fix-PMSF", "GTR20+C10opt-PMSF", "GTR20+C60fix-PMSF", "GTR20+C60opt-PMSF", "LG+C10fix-PMSF", "LG+C10opt-PMSF","LG+C60fix-PMSF", "LG+C60opt-PMSF", "Poisson+C10fix-PMSF", "Poisson+C10opt-PMSF","Poisson+C60fix-PMSF", "Poisson+C60opt-PMSF") ~ "CXX-PMSF",
    
    dataset %in% c("Poisson+UDM8fix-PMSF", "Poisson+UDM8opt-PMSF", "Poisson+UDM64fix-PMSF", "Poisson+UDM64opt-PMSF", "Poisson+UDM128fix-PMSF", "Poisson+UDM128opt-PMSF", "LG+UDM8fix-PMSF", "LG+UDM8opt-PMSF", "LG+UDM64fix-PMSF", "LG+UDM64opt-PMSF", "LG+UDM128fix-PMSF", "LG+UDM128opt-PMSF", "GTR20+UDM8fix-PMSF", "GTR20+UDM8opt-PMSF", "GTR20+UDM64fix-PMSF", "GTR20+UDM64opt-PMSF", "GTR20+UDM128fix-PMSF", "GTR20+UDM128opt-PMSF") ~ "UDM-PMSF",
    
    dataset %in% c("LG+MEOW10opt-PMSF", "LG+MEOW60opt-PMSF", "LG+MEOW120opt-PMSF", "Poisson+MEOW10opt-PMSF", "Poisson+MEOW60opt-PMSF", "Poisson+MEOW120opt-PMSF") ~ "MEOW-PMSF",
    
    dataset %in% c("Poisson+C60fix", "Poisson+C60opt", "LG+C60fix") ~ "C60",
    TRUE ~ NA_character_
  ),

    # Step 2: 添加 exchangeability 分组
    exchangeability = case_when(
      grepl("^Poisson", dataset) ~ "Poisson",
      grepl("^LG", dataset) ~ "LG",
      grepl("^GTR20", dataset) ~ "GTR20",
      TRUE ~ NA_character_
    ),

    # Step 3: 添加 weights 分组
    weights = case_when(
      grepl("fix", dataset, ignore.case = TRUE) ~ "fix",
      grepl("opt", dataset, ignore.case = TRUE) ~ "opt",
      TRUE ~ "default"
    ),

    # Step 4: 添加 profile 子模型名
    profile = case_when(
      grepl("C10", dataset) ~ "C10",
      grepl("C60", dataset) ~ "C60",
      grepl("UDM8", dataset) ~ "UDM8",
      grepl("UDM64", dataset) ~ "UDM64",
      grepl("UDM128", dataset) ~ "UDM128",
      grepl("MEOW10", dataset) ~ "MEOW10",
      grepl("MEOW60", dataset) ~ "MEOW60",
      grepl("MEOW120", dataset) ~ "MEOW120",
      TRUE ~ "CAT"
    )
  )

# 手动设置每个 model 的 profile 可视范围
filtered_data <- combined_data %>%
  mutate(
    profile = case_when(
      group == "CXX-PMSF" & profile %in% c("C10", "C60") ~ profile,
      group == "UDM-PMSF" & profile %in% c("UDM8", "UDM64", "UDM128") ~ profile,
      group == "MEOW-PMSF" & profile %in% c("MEOW10", "MEOW60", "MEOW120") ~ profile,
      group == "C60" & profile == "C60" ~ profile,
      group == "CAT-PMSF" & profile == "CAT" ~ profile,
      TRUE ~ NA_character_
    )
  ) %>%
  filter(!is.na(profile)) %>%
  mutate(
    group = factor(group, levels = c("CAT-PMSF", "CXX-PMSF", "UDM-PMSF", "MEOW-PMSF", "C60")),
    exchangeability = factor(exchangeability, levels = c("Poisson", "LG", "GTR20")),
    weights = factor(weights, levels = c("default", "fix", "opt"))
  ) %>%
  group_by(group) %>%
  mutate(profile = factor(profile, levels = unique(profile))) %>%
  ungroup()

# 1. 构造组合变量 profile_weight
filtered_data <- filtered_data %>%
  mutate(
    profile_weight = interaction(profile, weights, sep = "_"),
    profile = factor(profile, levels = unique(profile)),
    weights = factor(weights, levels = c("default", "fix", "opt"))
  )

# 2. 设置 profile_weight 为有序 factor，顺序按 profile -> weights 排列
profile_levels_ordered <- filtered_data %>%
  distinct(profile, weights) %>%
  arrange(profile, weights) %>%
  mutate(profile_weight = interaction(profile, weights, sep = "_")) %>%
  pull(profile_weight)

filtered_data <- filtered_data %>%
  mutate(profile_weight = factor(profile_weight, levels = profile_levels_ordered))

# 3. 构造横轴标签：每个 profile 只标记一次，其余为 ""
x_ticks <- filtered_data %>%
  distinct(profile, weights) %>%
  arrange(profile, weights) %>%
  group_by(profile) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(
    profile_weight = interaction(profile, weights, sep = "_"),
    label = as.character(profile)
  )

breaks_vec <- x_ticks$profile_weight
labels_vec <- x_ticks$label

# 4. 自定义颜色
weight_colors <- c(
  "default" = "grey70",
  "fix" = "#56B4E9",
  "opt" = "#E69F00"
)

# 5. 绘图
ggplot(filtered_data, aes(x = profile_weight, y = diversity, fill = weights)) +
  geom_violin(
    scale = "width", trim = FALSE,
    color = "black", linewidth = 0.3, width = 1
  ) +
  geom_boxplot(
    width = 0.15, outlier.shape = NA,
    linewidth = 0.4, fill = "white", color = "black"
  ) +
  facet_grid(
    rows = vars(exchangeability),
    cols = vars(group),
    switch = "y",
    scales = "free_x",
    space = "free_x"
  ) +
  scale_fill_manual(values = weight_colors) +
  scale_x_discrete(breaks = breaks_vec, labels = labels_vec) +
  labs(y = "Diversity", x = NULL, fill = "Weights") +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 0.5, size = 8),
    axis.text.y = element_text(size = 9),
    axis.title.x = element_blank(),
    axis.title.y = element_text(size = 12),
    strip.text.x.top = element_text(size = 10, face = "bold"),
    strip.text.y.left = element_text(size = 10, face = "bold"),
    strip.background = element_rect(fill = "grey90", color = "black", linewidth = 0.4),
    panel.spacing = unit(0, "lines"),
    panel.border = element_rect(color = "black", fill = NA, linewidth = 0.4),
    panel.grid.major.y = element_line(color = "grey80", linewidth = 0.25, linetype = "dashed"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor = element_blank(),
    axis.ticks.x = element_line(color = "black", linewidth = 0.4),
    axis.ticks.length = unit(0.15, "cm"),
    legend.position = "right",
    legend.key.size = unit(0.4, "cm"),
    legend.title = element_blank()
  )
```



## n. PMSF model

```{r}
Poisson_C60fixPMSF_homotree <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-C60fix-PMSF/homo_tree/Poisson_C60fixPMSFhomo/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_C60fixPMSF_complextree <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/Poisson-C60fix-PMSF/PoiC60_tree/Poisson_C60fixPMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_C60fixPMSF_homotree <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-C60fix-PMSF/LG_C60fixPMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_C60fixPMSF_complextree <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-C60fix-PMSF/LG_C60fixPMSFagain/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

Poisson_C60fixPMSF_homotree$dataset <- "Poisson+C60-PMSF"
Poisson_C60fixPMSF_complextree$dataset <- "Poisson+C60-PMSF(complex guide tree)"
LG_C60fixPMSF_homotree$dataset <- "LG+C60-PMSF"
LG_C60fixPMSF_complextree$dataset <- "LG+C60-PMSF(complex guide tree)"
```


## n. UDM model

```{r}
LG_UDM64HOCPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-UDM64HOC-PMSF/LG_UDM64HOCPMSF/lgudm64hocpmsf_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM64HCPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG-UDM64HC-PMSF/LG_UDM64HCPMSF/diversity_scores_bootstrapped_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM64NfixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG_UDM64NfixPMSF/lgudm64nfixpmsf_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM64BCfixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG_UDM64BCPMSF/lgudm64bcpmsf_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM64BNfixPMSF <- read.table("D:/8701/clade-profile-mixtures-2025/data/tardigrades (Giacomelli et al., 2024)/output_40taxa/LG_UDM64BNPMSF/lgudm64bnpmsf_data.txt_gaps", header = TRUE, sep = "\t", stringsAsFactors = FALSE)

LG_UDM64NfixPMSF$dataset <- "LG_UDM64NfixPMSF"
LG_UDM64BCfixPMSF$dataset <- "LG_UDM64-PMSF(Both-CLR)"
LG_UDM64BNfixPMSF$dataset <- "LG_UDM64-PMSF(Both-None)"
LG_UDM64HOCPMSF$dataset <- "LG+UDM64-PMSF"
LG_UDM64HCPMSF$dataset <- "LG+UDM64-PMSF(HSSP-CLR)"
```

